// server.js - REVISED using Express.js

const express = require('express');
const app = express();
const PORT = process.env.PORT || 3000; 

// --- 1. CONFIGURE STATIC FILE SERVING ---
// This tells Express to look inside the 'public' directory
// for any static assets (images, CSS, etc.).
app.use(express.static('public')); 
// ----------------------------------------

// --- Application Data ---
const userData = {
    fullName: "Julie Anne L. Sarsale",           
    classSection: "BSIT SM 4101",           
    inspirationalQuote: "The only way to do great work is a love what you do. - Steve Jobs",
    // 2. Updated URL to point to the local file in the /public folder
    placeholderPictureURL: "/JulieImage.jpg" 
};

// --- HTML Generation Function ---
const generateHtmlResponse = (data) => {
    return `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Codespaces Node.js App</title>
    <style>
        /* CSS is fully contained here (same as before) */
        :root {
            --primary-color: #007bff; /* Blue */
            --background-color: #f4f7f6;
            --card-background: #ffffff;
            --text-color: #333;
        }
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 0;
            padding: 0;
            background-color: var(--background-color);
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
            color: var(--text-color);
        }
        .container {
            width: 90%;
            max-width: 500px;
            padding: 40px;
            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.1);
            border-radius: 20px;
            background-color: var(--card-background);
            text-align: left;
            transition: transform 0.3s ease-in-out;
        }
        .browser-header {
            width: 100%;
            max-width: 500px;
            background: #e9ecef;
            border-top-left-radius: 8px;
            border-top-right-radius: 8px;
            padding: 8px 15px;
            display: flex;
            align-items: center;
            justify-content: flex-start;
            margin-bottom: 0px;
            border-bottom: none;
            color: #6c757d;
            font-size: 0.8em;
        }
        .profile-section {
            display: flex;
            align-items: center;
            margin-bottom: 20px;
            padding-top: 15px;
        }
        .profile-img {
            border-radius: 50%; /* Makes it circular */
            /* Ensure the image fits the container properly */
            object-fit: cover; 
            width: 70px;
            height: 70px;
            margin-right: 20px;
            border: 3px solid var(--primary-color); 
        }
        h2 {
            color: var(--primary-color);
            margin-bottom: 5px;
            font-size: 1.8em;
            display: flex;
            align-items: center;
        }
        h2 svg {
            margin-right: 10px;
        }
        p {
            font-size: 1.0em;
            margin: 5px 0;
        }
        .info-item {
            padding: 15px 0;
            border-top: 1px solid #eee;
        }
        .info-label {
            font-size: 0.9em;
            color: #666;
            margin-bottom: 3px;
        }
        .info-data {
            font-weight: bold;
            font-size: 1.1em;
            color: #333;
        }
        .quote {
            font-style: italic;
            color: #333;
            font-size: 1.1em;
            margin-top: 25px;
            padding: 15px;
            border-left: 10px solid var(--primary-color); 
            background-color: #f9f9f9;
        }
        .quote-label {
            font-size: 0.9em;
            color: var(--primary-color);
            margin-bottom: 5px;
            font-style: normal;
            font-weight: 600;
        }
    </style>
</head>
<body>
    <div class="browser-header">
        Codespaces Node.js App | This page was generated by a Node.js server.
    </div>
    
    <div class="container">
        <h2>
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-user"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path><circle cx="12" cy="7" r="4"></circle></svg>
            Welcome to My Codespace App
        </h2>
        <p style="font-size: 0.9em; color: #666;">This page was generated by a simple Node.js server.</p>

        <div class="profile-section">
            <img class="profile-img" src="${data.placeholderPictureURL}" alt="Your Image">
            <div>
                <div class="info-label">Full Name</div>
                <div class="info-data">${data.fullName}</div>
            </div>
        </div>

        <div class="info-item">
            <div class="info-label">Class Section</div>
            <div class="info-data">${data.classSection}</div>
        </div>

        <div class="quote">
            <div class="quote-label">Inspirational Quote</div>
            "${data.inspirationalQuote.split(' - ')[0]}"<br>
            <span style="display: block; text-align: right; margin-top: 5px; font-weight: 500;">- ${data.inspirationalQuote.split(' - ')[1]}</span>
        </div>

    </div>
</body>
</html>
    `;
};

// --- Define the Root Route Handler ---
app.get('/', (req, res) => {
    // Set the Content-Type header to tell the browser it's HTML
    res.setHeader('Content-Type', 'text/html');
    // Send the generated HTML as the response body
    res.send(generateHtmlResponse(userData));
});


// --- Start the Server ---
app.listen(PORT, () => {
    console.log(`Server running on port ${PORT}`);
    console.log('Access the application via the Codespaces "Ports" tab.');
});